### ISSUE TITLE
Generate base/abstract class defining common UI themes

### ISSUE THREAD

**Issue by diegovillafuerte1** [diegovillafuerte1/valorant-clutch-bind#1]
Every reused component should have a base/abstract class where we can define color schemes and other common themes used throughout the application.

e.g. all "window" panels (i call a "window" the thing that contains the "Audio Sources" & "Toggle Voice") should inherit a base class/control that sets all of the properties (FlatStyle, Back Color, etc.), overidable ofc
All "Submenu" buttons inherit base submenubutton
All "Menu" buttons inherit base menuButton...
MenuPanelBase
SubMenuPanelBase

i think this is a use case for an "Extended Control" or "user Control", need to look up.  Probably more along the lines of extending a winforms control 
alot of the UI stuff is handled in the VS form designer.  Colors and style and docking and everything.  I personally prefer certain UI initializations/properties to be set programmatically, which is why i suggest this story.

menu hierarchy works like (i.e. SideMenuPanel contains LogoPanel, SettingsButton, SettingsPanel)

```
SideMenuPanel             //entire left menu
     LogoPanel            //top blank black space
     SettingsButton       //self describing
     SettingsPanel        //panel that we show/hide when settings button is clicked
         AudioButton      //Shows the audio settings window
         BindsButton      //shows the binds /hotkeys window
```

**Comment by WitnessMei** [comment]
Done

Future controls added that need to be themed should have their own extended class implementing IThemedControl
